name: Getting-input-as-a-json-and-run-the-databricks-job

on: 
  workflow_dispatch: 
    inputs: 
      env: 
        type: choice
        required: true
        description: Select the Environment
        options:
          - expl
          - dev
          - qa
          - prod

      json_data:
              description: 'JSON Data to parse'
              required: true


env: 
  json_data: ${{ github.event.input.json_data }}
  json_data_2 = { "name": "John Doe", "email": "johndoe@example.com","age": 30,"city": "New York"}

jobs:
  run-databricks-job:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Code
        uses: actions/checkout@main


      - name: Access parsed values
        run: |
          set -exo pipefail 
          name=$(echo $json_data | jq -r '.name')
          email=$(echo $json_data_2 | jq -r '.email')
          echo "Value of 'name' property: $name"
          echo "Value of the 'email': $email" 
          echo "$email" 
          echo $name
