name: Getting-input-as-a-json-and-run-the-databricks-job

on: 
  workflow_dispatch: 
    inputs: 
      env: 
        type: choice
        required: true
        description: Select the Environment
        options:
          - expl
          - dev
          - qa
          - prod

      json_data:
              description: 'JSON Data to parse'
              required: true

jobs:
  run-databricks-job:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Code
        uses: actions/checkout@main

      - name: parse json data 
        run: | 
          echo ${{ github.event.inputs.json_data }}
