name: Getting-input-as-a-json-and-run-the-databricks-job

on: 
  workflow_dispatch: 
    inputs: 
      env: 
        type: choice
        required: true
        description: Select the Environment
        options:
          - Select Environment
          - expl
          - dev
          - qa
          - prod

jobs:
  run-databricks-job:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Code
        uses: actions/checkout@main