name: Getting-input-as-a-json-and-run-the-databricks-job

on: 
  workflow_dispatch: 
    inputs: 
      env: 
        type: choice
        required: true
        description: Select the Environment
        options:
          - expl
          - dev
          - qa
          - prod

      json_data:
              description: 'JSON Data to parse'
              required: true
              type: dict 


env: 
  json_data: ${{ github.event.input.json_data }}

jobs:
  run-databricks-job:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Code
        uses: actions/checkout@main

      - name: checking: 
        run: echo "Json is $json_data!"

      - name: Access parsed values
        run: |
          set -exo pipefail 
          echo $json_data
          name=$(echo $json_data | jq -r '.name')
          email=$(echo $json_data | jq -r '.email')
          echo "Value of 'name' property: $name"
          echo "Value of the 'email': $email" 
          echo "$email" 
          echo $name
