name: Getting-input-as-a-json-and-run-the-databricks-job

on: 
  workflow_dispatch: 
    inputs: 
      env: 
        type: choice
        required: true
        description: Select the Environment
        options:
          - expl
          - dev
          - qa
          - prod

      json_data:
              description: 'JSON Data to parse'
              required: true


env: 
  json_data: ${{ github.event.input.json_data }}

jobs:
  run-databricks-job:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Code
        uses: actions/checkout@main

      - name: parse json data 
        run: | 
          set -exo pipefail 
          echo "Raw JSON input: $json_data"
          parsed_json=$json_data
          echo "Parsed JSON:"
          echo "$parsed_json"

      - name: Access parsed values (example)
        run: |
          set -exo pipefail 
          name=$(echo $parsed_json | jq -r '.name')
          echo "Value of 'name' property: $name"
